### ISSUE TITLE
How to configure typeahead with Angular-cli

### ISSUE THREAD

**Issue by vibingopal** [brinkmanjg/ng2-typeahead#19]
Hi,

Please help on how to configure typeahead with angularcli. Iam using angular cli and i have installed typeahead with npm command.Now how to import that and configure in the component. since there is no systemjs in angular-cli.

**Comment by RoopeHakulinen** [comment]
Usage with Angular CLI works without any additional configuration just like it is described in the README.md.

**Comment by joshterrill** [comment]
Same.

**Comment by skgyan** [comment]
+1

**Comment by rhermans** [comment]
I added typeahead in the app.module.ts
import { Typeahead } from 'ng2-typeahead'; 
and add it to the @NgModule
@NgModule({
  declarations: [
    ...
    Typeahead
  ],
then you can use it in any component.template  and it works.

**Comment by jineshmistry** [comment]
@rhermans I follow the step you mentioned above. But i am still getting error. See this. 
![capture](https://user-images.githubusercontent.com/12869314/28171519-465605e8-6806-11e7-8b61-98a9194ca34e.PNG)

**Comment by vibingopal** [comment]
I have implemented the typeahead feature with Material 2 Autocomplete design.

https://material.angular.io/components
