### ISSUE TITLE
Databinding for existing value

### ISSUE THREAD

**Issue by RichardGrundy** [brinkmanjg/ng2-typeahead#5]
Hello,

would like to thank you for a great typehead. Can you tell me if it is possible to have the input show any previously selected data? For example I can set the value in my form but when I come to edit an existing record the typeahead does not fill the existing value. 

If we could bind an ng-model maybe?

Thanks

Richard

**Comment by brinkmanjg** [comment]
I updated the component to use the control value accessor pattern. Hopefully this works for your use case. I successfully tested it with a simple form.
