### ISSUE TITLE
adjustments in systemjs.config.js to run example code

### ISSUE THREAD

**Issue by meier297** [brinkmanjg/ng2-typeahead#7]
You should also mentioned that changes in _**systemjs.config.js**_ are necessary.

I had to make following adjustments:

```js
  var map = {
	...
	'ng2-typeahead':              'node_modules/ng2-typeahead',								
  };
  ...
  var packages = {
	...
	'ng2-typeahead':              { main: 'ng2-typeahead.js', defaultExtension: 'js' }
  };
```

**Comment by brinkmanjg** [comment]
Noted in README. Not sure if this still applies but it can't hurt. Thanks!

**Comment by moutono** [comment]
Thanks for this.
However had to make this small change:

`    var packages = {
        ...
        'ng2-typeahead': { **main: 'index.js'**, defaultExtension: 'js' }
    };`
